class: middle, center

### 9.3

# To panic! or Not To panic!

---

class: left

# Panic! or Not

- There is no way to recover after `panic!`

- `panic!` can be called for any error situation, recoverable or unrecoverable

- But, you are making the decision on behalf of the code calling your code that
  the error is unrecoverable

- `Result` will give the option to the callig code to decide wether to panic or not

- Returning `Result` is a good default choice

---

class: left

# Places to `Panic!`

It’s Perfectly fine to Panic in

- Examples

- Prototype Code and

- Tests

---

class: left

# Cases in Which You Have More Information Than the Compiler

- use `unwrap` when you can ensure that Result will have an Ok value, but
  the logic isn’t something compiler understands

```rust
#![allow(unused_variables)]
fn main() {
use std::net::IpAddr;

let home: IpAddr = "127.0.0.1".parse().unwrap();
}
```

[play](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=1550c40f386b2be6839747ee98141d10)

---

class: left

# Guidelines for Error Handling

When it’s possible that your code could end up in a bad state

**bad state** is is when some assumption, guarantee, contract, or invariant has been broken, such as when invalid values, contradictory values, or missing values are passed to your code

- The bad state is not something that’s expected to happen occasionally

- Your code after this point needs to rely on not being in this bad state

- There’s not a good way to encode this information in the types you use

---

class: left

# panic

- to inform the consumer of your code in case of invalid input

- in case the code you are consuming does something which you can't fix

eg; rust std lib panics in case of out of bounds memory access

---

class: left

# Creating Custom Types for Validation

Data has constraints they can be enforced in many ways...

```rust
loop {
    // --snip--

    let guess: i32 = match guess.trim().parse() {
        Ok(num) => num,
        Err(_) => continue,
    };

    if guess < 1 || guess > 100 {
        println!("The secret number will be between 1 and 100.");
        continue;
    }

    match guess.cmp(&secret_number) {
    // --snip--
}
```

- type (i32) validates that the input is a number
- if expression ensures the number is in the agreed range

---

class: left

# custom types

```rust
#![allow(unused_variables)]
fn main() {
    pub struct Guess {
        value: i32,
    }
    impl Guess {
        pub fn new(value: i32) -> Guess {
            if value < 1 || value > 100 {
                panic!("Guess value must be between 1 and 100, got {}.", value);
            }
            Guess {
                value
            }
        }
        pub fn value(&self) -> i32 {
            self.value
        }
    }
}
```

- `Guess` struct that has a field named `value` that holds an i32

- associated function `new` on Guess creates instances of Guess values

- `value` is private and can be get it using a getter function `value`

---

class: left

# Summary

- `panic!` - state can’t be handled and the process has to stop

- `Result` - enum tells you to handle potential success or failure
